### ISSUE TITLE
Restoring file that doesn't exist anymore should be transparent

### ISSUE THREAD

**Issue by beaufortfrancois** [GoogleChromeLabs/text-app#236]
- Open a file in the Text App
- Press `<Ctrl>+W` to quit the App and force the Text App to retain this file entry
- Reopen the Text App
- An error occurs in the background page

``` javascript
Error in response to runtime.getBackgroundPage: Error: Invocation of form fileSystem.getDisplayPath(undefined, function) doesn't match definition fileSystem.getDisplayPath(object entry, function callback)
    at TextApp.init (chrome-extension://bfhnlkdphkbmcedgoidmafpllbenjccm/js/app.js:46:18)
    at l (chrome-extension://bfhnlkdphkbmcedgoidmafpllbenjccm/lib/jquery-1.8.3.min.js:2:16996)
    at Object.c.fireWith [as resolveWith] (chrome-extension://bfhnlkdphkbmcedgoidmafpllbenjccm/lib/jquery-1.8.3.min.js:2:17783)
    at Function.v.extend.ready (chrome-extension://bfhnlkdphkbmcedgoidmafpllbenjccm/lib/jquery-1.8.3.min.js:2:12504)
    at HTMLDocument.A (chrome-extension://bfhnlkdphkbmcedgoidmafpllbenjccm/lib/jquery-1.8.3.min.js:2:9909) _generated_background_page.html:1
Error in response to runtime.getBackgroundPage: TypeError: Cannot read property 'background' of undefined
    at TextApp.init (chrome-extension://bfhnlkdphkbmcedgoidmafpllbenjccm/js/app.js:46:18)
    at l (chrome-extension://bfhnlkdphkbmcedgoidmafpllbenjccm/lib/jquery-1.8.3.min.js:2:16996)
    at Object.c.fireWith [as resolveWith] (chrome-extension://bfhnlkdphkbmcedgoidmafpllbenjccm/lib/jquery-1.8.3.min.js:2:17783)
    at Function.v.extend.ready (chrome-extension://bfhnlkdphkbmcedgoidmafpllbenjccm/lib/jquery-1.8.3.min.js:2:12504)
    at HTMLDocument.A (chrome-extension://bfhnlkdphkbmcedgoidmafpllbenjccm/lib/jquery-1.8.3.min.js:2:9909) _generated_background_page.html:1
```

**Comment by BugsNash** [comment]
Changing this to bug as the behaviour of the app is to show 'Error' and have no open files when you open it and it doesn't successfully open any files it expects.
